# Generated by Django 4.2.7 on 2023-11-27 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saasapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='user',
            new_name='user_id',
        ),
    ]
