# Generated by Django 4.2.7 on 2023-11-27 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saasapp', '0002_rename_user_cartitem_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
